export const BASE_API = process.env.NEXT_PUBLIC_BASE_API as string
export const SCREEN_S = 400;
export const SCREEN_SM = 507;
export const SCREEN_MD = 700;
export const SCREEN_LG = 900;
export const SCREEN_L = 1100;
export const SCREEN_XL = 1300;
export const SCREEN_XXL = 1400;
export const SCREEN_XXXL = 1600;